Update to Gradle 4.10
researchgate/gradle-release pull request #331
Opened 2020-04-05 20:21 UTC by rnc

1.12 is incompatible with later versions (detected by importing into IntelliJ) ; it is 8 years old. 4.10 is 2 years old - it is fairly common along with 5.x in general usage.

2020-06-25 06:06 UTC, Hillkorn commented
Let's use 4.10.3 instead

2020-07-09 07:41 UTC, Hillkorn commented
Hey tests are failing because the sprock version requires the old groovy version but gradle 4.10.3 comes with a newer one. Can you please upgrade?

Thanks :)

2020-07-26 09:35 UTC, rnc commented
Apologies I missed this message. Trying locally, upgrading the relevant libraries the tests fail. I will see if I can find some time to look into this.

2020-07-28 21:15 UTC, rnc commented
I've taken a brief look at this tonight. The testing framework for the integration tests predates the Gradle TestKit and has a lot of issues when attempting to update it - `userHome` directories are created which breaks the tests ( but ProjectBuilder could use `withGradleUserHomeDir` to work around that ). The gradle task graph is not populated which leads to numerous breakages when updating to a later gradle version.

2020-11-13 18:44 UTC, nngo requested changes
I think you should use the "bin" vs "all" distro, i.e.
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.3-bin.zip`

2020-11-13 18:45 UTC, nngo commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.3-all.zip
use the bin distro, instead of the all distro, since it will be a smaller download

2020-11-13 18:47 UTC, nngo commented on gradle/wrapper/gradle-wrapper.properties
> +#Sun Apr 05 21:14:59 BST 2020
should also include `distributionSha256Sum=` for additional security

2020-11-13 18:53 UTC, nngo commented
Would be it safer to first upgrade to Gradle 2.14.1 (latest 2.x release), then cut a release of this plugin.
Then followup and upgrade to Gradle 3.5 (latest 3.x release) then cut another release of this plugin?

2022-06-20 20:41 UTC, Hillkorn commented
Upgraded to 6 in main branch. Will release it soon.

2022-06-20 20:41 UTC, closed without merging